import { useEffect } from "react";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";

export default function PrivacyPolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <main className="min-h-screen w-full">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        {/* Header Section */}
        <div className="text-center mb-12">
          <Badge
            variant="outline"
            className="p-2 px-4 rounded-full bg-background"
          >
            Last updated: July 11, 2025
          </Badge>
          <h1 className="text-5xl font-bold tracking-tight mt-4 font-secondary">
            Privacy Policy
          </h1>
        </div>

        {/* Introduction */}
        <section className="mb-10">
          <p className="leading-relaxed text-muted-foreground mb-6">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        <Separator className="my-10" />

        {/* Interpretation and Definitions */}
        <section className="mb-10">
          <h2 className="text-3xl font-bold mb-8 font-secondary">
            Interpretation and Definitions
          </h2>

          <div className="mb-8">
            <h3 className="text-2xl font-semibold mb-2">Interpretation</h3>
            <p className="text-muted-foreground leading-relaxed">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>

          <div>
            <h3 className="text-2xl font-semibold mb-2">Definitions</h3>
            <p className="text-muted-foreground mb-4">
              For the purposes of this Privacy Policy:
            </p>

            <div className="space-y-4">
              {[
                {
                  term: "Account",
                  definition:
                    "means a unique account created for You to access our Service or parts of our Service.",
                },
                {
                  term: "Affiliate",
                  definition:
                    'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                },
                {
                  term: "Application",
                  definition:
                    "refers to EZO LENS, the software program provided by the Company.",
                },
                {
                  term: "Company",
                  definition:
                    '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Ezwiiz Frontier Systems Private Limited, H NO 2-1-349/31/1 GREEN, FIELD COLONY, NAGOLE, Gsi(Sr) Bandlaguda, Hayathnagar, Hyderabad- 500068, Telangana.',
                },
                {
                  term: "Country",
                  definition: "refers to: Telangana, India",
                },
                {
                  term: "Device",
                  definition:
                    "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
                },
                {
                  term: "Personal Data",
                  definition:
                    "is any information that relates to an identified or identifiable individual.",
                },
                {
                  term: "Service",
                  definition: "refers to the Application.",
                },
                {
                  term: "Service Provider",
                  definition:
                    "means any natural or legal person who processes the data on behalf of the Company.",
                },
                {
                  term: "Usage Data",
                  definition:
                    "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
                },
                {
                  term: "You",
                  definition:
                    "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
                },
              ].map((item, index) => (
                <div
                  key={index}
                  className="border-l-4 border-primary/20 pl-4 py-2"
                >
                  <span className="font-semibold text-foreground">
                    {item.term}:
                  </span>{" "}
                  <span className="text-muted-foreground">
                    {item.definition}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* Collecting and Using Personal Data */}
        <section className="mb-10">
          <h2 className="text-3xl font-bold mb-8 font-secondary">
            Collecting and Using Your Personal Data
          </h2>

          <div className="mb-8">
            <h3 className="text-2xl font-semibold mb-4">
              Types of Data Collected
            </h3>

            <div className="mb-8">
              <h4 className="text-xl font-semibold mb-2">Personal Data</h4>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul className="space-y-2 ml-6">
                {[
                  "Email address",
                  "First name and last name",
                  "Phone number",
                  "Address, State, Province, ZIP/Postal code, City",
                ].map((item, index) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-primary rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-muted-foreground">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="mb-8">
              <h4 className="text-xl font-semibold mb-2">Usage Data</h4>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                Usage Data may include information such as Your Device's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that You visit, the
                time and date of Your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                When You access the Service by or through a mobile device, We
                may collect certain information automatically, including, but
                not limited to, the type of mobile device You use, Your mobile
                device unique ID, the IP address of Your mobile device, Your
                mobile operating system, the type of mobile Internet browser You
                use, unique device identifiers and other diagnostic data.
              </p>
            </div>

            <div className="mb-8">
              <h4 className="text-xl font-semibold mb-4">
                Information Collected while Using the Application
              </h4>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                While using Our Application, in order to provide features of Our
                Application, We may collect, with Your prior permission:
              </p>
              <ul className="space-y-2 ml-6 mb-4">
                {[
                  "Information regarding your location",
                  "Pictures and other information from your Device's camera and photo library",
                ].map((item, index) => (
                  <li key={index} className="flex items-start">
                    <div className="w-2 h-2 bg-primary rounded-full mt-2 mr-3 flex-shrink-0"></div>
                    <span className="text-muted-foreground">{item}</span>
                  </li>
                ))}
              </ul>
              <p className="text-muted-foreground mb-4 leading-relaxed">
                We use this information to provide features of Our Service, to
                improve and customize Our Service. The information may be
                uploaded to the Company's servers and/or a Service Provider's
                server or it may be simply stored on Your device.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                You can enable or disable access to this information at any
                time, through Your Device settings.
              </p>
            </div>
          </div>

          <div className="mb-8">
            <h3 className="text-2xl font-semibold mb-2">
              Use of Your Personal Data
            </h3>
            <p className="text-muted-foreground mb-4 leading-relaxed">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="space-y-3 ml-6">
              {[
                "To provide and maintain our Service, including to monitor the usage of our Service.",
                "To manage Your Account: to manage Your registration as a user of the Service.",
                "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.",
                "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
                "To provide You with news, special offers and general information about other goods, services and events.",
                "To manage Your requests: To attend and manage Your requests to Us.",
                "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.",
                "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.",
              ].map((item, index) => (
                <li key={index} className="flex items-start">
                  <div className="w-2 h-2 bg-primary rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span className="text-muted-foreground leading-relaxed">
                    {item}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div className="mb-8">
            <p className="text-muted-foreground mb-4 leading-relaxed">
              We may share Your personal information in the following
              situations:
            </p>
            <ul className="space-y-3 ml-6">
              {[
                {
                  title: "With Service Providers:",
                  content:
                    "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.",
                },
                {
                  title: "For business transfers:",
                  content:
                    "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
                },
                {
                  title: "With Affiliates:",
                  content:
                    "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.",
                },
                {
                  title: "With business partners:",
                  content:
                    "We may share Your information with Our business partners to offer You certain products, services or promotions.",
                },
                {
                  title: "With other users:",
                  content:
                    "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
                },
                {
                  title: "With Your consent:",
                  content:
                    "We may disclose Your personal information for any other purpose with Your consent.",
                },
              ].map((item, index) => (
                <li key={index} className="flex items-start">
                  <div className="w-2 h-2 bg-primary rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span className="text-muted-foreground leading-relaxed">
                    <span className="font-semibold text-foreground">
                      {item.title}
                    </span>{" "}
                    {item.content}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <Separator className="my-10" />

        {/* Additional Sections */}
        <section className="space-y-10">
          {[
            {
              title: "Retention of Your Personal Data",
              content: [
                "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
                "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
              ],
            },
            {
              title: "Transfer of Your Personal Data",
              content: [
                "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to and maintained on computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
                "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
                "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
              ],
            },
            {
              title: "Delete Your Personal Data",
              content: [
                "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
                "Our Service may give You the ability to delete certain information about You from within the Service.",
                "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
                "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
              ],
            },
            {
              title: "Security of Your Personal Data",
              content: [
                "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
              ],
            },
            {
              title: "Children's Privacy",
              content: [
                "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
                "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
              ],
            },
            {
              title: "Links to Other Websites",
              content: [
                "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
                "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
              ],
            },
            {
              title: "Changes to this Privacy Policy",
              content: [
                "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
                'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
                "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
              ],
            },
          ].map((section, index) => (
            <div key={index}>
              <h3 className="text-2xl font-semibold mb-2">{section.title}</h3>
              <div className="space-y-4">
                {section.content.map((paragraph, pIndex) => (
                  <p
                    key={pIndex}
                    className="text-muted-foreground leading-relaxed"
                  >
                    {paragraph}
                  </p>
                ))}
              </div>
            </div>
          ))}

          {/* Disclosure Section */}
          <div>
            <h3 className="text-2xl font-semibold mb-6 font-secondary">
              Disclosure of Your Personal Data
            </h3>

            <div className="space-y-6">
              <div>
                <h4 className="text-xl font-semibold mb-3">
                  Business Transactions
                </h4>
                <p className="text-muted-foreground leading-relaxed">
                  If the Company is involved in a merger, acquisition or asset
                  sale, Your Personal Data may be transferred. We will provide
                  notice before Your Personal Data is transferred and becomes
                  subject to a different Privacy Policy.
                </p>
              </div>

              <div>
                <h4 className="text-xl font-semibold mb-3">Law Enforcement</h4>
                <p className="text-muted-foreground leading-relaxed">
                  Under certain circumstances, the Company may be required to
                  disclose Your Personal Data if required to do so by law or in
                  response to valid requests by public authorities (e.g. a court
                  or a government agency).
                </p>
              </div>

              <div>
                <h4 className="text-xl font-semibold mb-3">
                  Other Legal Requirements
                </h4>
                <p className="text-muted-foreground mb-4 leading-relaxed">
                  The Company may disclose Your Personal Data in the good faith
                  belief that such action is necessary to:
                </p>
                <ul className="space-y-2 ml-6">
                  {[
                    "Comply with a legal obligation",
                    "Protect and defend the rights or property of the Company",
                    "Prevent or investigate possible wrongdoing in connection with the Service",
                    "Protect the personal safety of Users of the Service or the public",
                    "Protect against legal liability",
                  ].map((item, index) => (
                    <li key={index} className="flex items-start">
                      <div className="w-2 h-2 bg-primary rounded-full mt-2 mr-3 flex-shrink-0"></div>
                      <span className="text-muted-foreground">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Contact Section */}
          <div className="bg-primary/10 p-6 rounded-lg">
            <h3 className="text-2xl font-semibold mb-2 font-secondary">
              Contact Us
            </h3>
            <p className="text-muted-foreground mb-4 leading-relaxed">
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <ul className="space-y-">
              {[
                {
                  label: "Email",
                  value: "info@ezohr.com",
                  href: "mailto:info@ezohr.com",
                },
                {
                  label: "Website",
                  value: "www.ezohr.com",
                  href: "https://www.ezohr.com",
                },
                {
                  label: "Phone",
                  value: "+91-9652009244",
                  href: "tel:+919652009244",
                },
              ].map((contact, index) => (
                <li key={index} className="flex items-center">
                  <span className="font-semibold text-foreground w-20">
                    {contact.label}:
                  </span>
                  <a href={contact.href} className="text-muted-foreground">
                    {contact.value}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </section>
      </div>
    </main>
  );
}
